/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package maturita.maturita;

/**
 *
 * @author Marek
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        display = new javax.swing.JLabel();
        bargraf_slider = new javax.swing.JSlider();
        bargraf = new javax.swing.JLabel();
        gren_diode = new javax.swing.JLabel();
        red_diode = new javax.swing.JLabel();
        hostaname = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        trim1_disp = new javax.swing.JLabel();
        trim2_disp = new javax.swing.JLabel();
        trim1_bar = new javax.swing.JProgressBar();
        trim2_bar = new javax.swing.JProgressBar();
        temp_disp = new javax.swing.JLabel();
        TEMP = new javax.swing.JLabel();
        TRIM1 = new javax.swing.JLabel();
        TRIM2 = new javax.swing.JLabel();
        PORTD_label = new javax.swing.JLabel();
        PORTB_label = new javax.swing.JLabel();
        PORTC_label = new javax.swing.JLabel();
        PORTA_label1 = new javax.swing.JLabel();
        PORTA = new javax.swing.JLabel();
        PORTB = new javax.swing.JLabel();
        PORTC = new javax.swing.JLabel();
        PORTD = new javax.swing.JLabel();
        PORTA_arrow = new javax.swing.JLabel();
        PORTB_arrow = new javax.swing.JLabel();
        PORTC_arrow = new javax.swing.JLabel();
        PORTD_arrow = new javax.swing.JLabel();
        ports_background = new javax.swing.JLabel();
        top_background = new javax.swing.JLabel();
        PHOTO = new javax.swing.JLabel();
        BT0 = new javax.swing.JToggleButton();
        BT1 = new javax.swing.JToggleButton();
        BT2 = new javax.swing.JToggleButton();
        BT3 = new javax.swing.JToggleButton();
        BT4 = new javax.swing.JToggleButton();
        BT5 = new javax.swing.JToggleButton();
        BT6 = new javax.swing.JToggleButton();
        BT7 = new javax.swing.JToggleButton();
        PHOTO_LABEL = new javax.swing.JLabel();
        trims_background = new javax.swing.JLabel();
        buttons_background = new javax.swing.JLabel();
        header = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        display.setFont(new java.awt.Font("Cambria", 0, 72)); // NOI18N
        display.setForeground(java.awt.Color.red);
        display.setText("1234");
        display.setOpaque(true);
        getContentPane().add(display, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 25, 160, 80));

        bargraf_slider.setMaximum(10);
        bargraf_slider.setOrientation(javax.swing.JSlider.VERTICAL);
        bargraf_slider.setValue(1);
        bargraf_slider.setOpaque(false);
        getContentPane().add(bargraf_slider, new org.netbeans.lib.awtextra.AbsoluteConstraints(545, 12, -1, 110));

        bargraf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maturita/maturita/bargraf_1.png"))); // NOI18N
        getContentPane().add(bargraf, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 22, 20, 86));

        gren_diode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maturita/green_diode.png"))); // NOI18N
        getContentPane().add(gren_diode, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 40, 40));

        red_diode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maturita/maturita/red_diode.png"))); // NOI18N
        red_diode.setText("jLabel1");
        getContentPane().add(red_diode, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 40, 40));

        hostaname.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        hostaname.setText("spinet");
        getContentPane().add(hostaname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 100, 40));

        jButton1.setText("Connect");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));

        trim1_disp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maturita/maturita/white.png"))); // NOI18N
        getContentPane().add(trim1_disp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 120, 60));

        trim2_disp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maturita/maturita/white.png"))); // NOI18N
        trim2_disp.setText("jLabel1");
        getContentPane().add(trim2_disp, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 120, 60));
        getContentPane().add(trim1_bar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 120, -1));
        getContentPane().add(trim2_bar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 120, -1));

        temp_disp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maturita/maturita/white.png"))); // NOI18N
        temp_disp.setText("jLabel1");
        getContentPane().add(temp_disp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 120, 40));

        TEMP.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        TEMP.setText("TEMP");
        getContentPane().add(TEMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, 24));

        TRIM1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        TRIM1.setText("TRIM1");
        getContentPane().add(TRIM1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, 24));

        TRIM2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        TRIM2.setText("TRIM2");
        getContentPane().add(TRIM2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, 24));

        PORTD_label.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        PORTD_label.setForeground(java.awt.Color.darkGray);
        PORTD_label.setText("PORT D:");
        getContentPane().add(PORTD_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 50, 20));

        PORTB_label.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        PORTB_label.setForeground(java.awt.Color.darkGray);
        PORTB_label.setText("PORT B:");
        getContentPane().add(PORTB_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 50, 20));

        PORTC_label.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        PORTC_label.setForeground(java.awt.Color.darkGray);
        PORTC_label.setText("PORT A:");
        getContentPane().add(PORTC_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 50, 20));

        PORTA_label1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        PORTA_label1.setForeground(java.awt.Color.darkGray);
        PORTA_label1.setText("PORT C:");
        getContentPane().add(PORTA_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 50, 20));

        PORTA.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        PORTA.setForeground(java.awt.Color.darkGray);
        PORTA.setText("IN");
        PORTA.setToolTipText("");
        getContentPane().add(PORTA, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 36, 34));

        PORTB.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        PORTB.setForeground(java.awt.Color.darkGray);
        PORTB.setText("IN");
        PORTB.setToolTipText("");
        getContentPane().add(PORTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 36, 34));

        PORTC.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        PORTC.setForeground(java.awt.Color.darkGray);
        PORTC.setText("IN");
        PORTC.setToolTipText("");
        getContentPane().add(PORTC, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 36, 34));

        PORTD.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        PORTD.setForeground(java.awt.Color.darkGray);
        PORTD.setText("IN");
        PORTD.setToolTipText("");
        getContentPane().add(PORTD, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 36, 34));

        PORTA_arrow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maturita/maturita/left_arrow.png"))); // NOI18N
        getContentPane().add(PORTA_arrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, 32, 32));

        PORTB_arrow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maturita/maturita/left_arrow.png"))); // NOI18N
        getContentPane().add(PORTB_arrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 230, 32, 32));

        PORTC_arrow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maturita/maturita/left_arrow.png"))); // NOI18N
        getContentPane().add(PORTC_arrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, 32, 32));

        PORTD_arrow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maturita/maturita/left_arrow.png"))); // NOI18N
        getContentPane().add(PORTD_arrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 32, 32));

        ports_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maturita/maturita/patern2.jpg"))); // NOI18N
        getContentPane().add(ports_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 210, 205));

        top_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maturita/dark_gray.png"))); // NOI18N
        getContentPane().add(top_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 720, 92));

        PHOTO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maturita/maturita/yellow_green.png"))); // NOI18N
        getContentPane().add(PHOTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 265, 56, 55));

        BT0.setText("BT1");
        BT0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT0ActionPerformed(evt);
            }
        });
        getContentPane().add(BT0, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 56, 55));

        BT1.setText("BT2");
        BT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT1ActionPerformed(evt);
            }
        });
        getContentPane().add(BT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 56, 55));

        BT2.setText("BT3");
        BT2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT2ActionPerformed(evt);
            }
        });
        getContentPane().add(BT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, 56, 55));

        BT3.setText("BT4");
        BT3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT3ActionPerformed(evt);
            }
        });
        getContentPane().add(BT3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, 56, 55));

        BT4.setText("BT5");
        BT4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT4ActionPerformed(evt);
            }
        });
        getContentPane().add(BT4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, 56, 55));

        BT5.setText("BT6");
        BT5.setToolTipText("");
        BT5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT5ActionPerformed(evt);
            }
        });
        getContentPane().add(BT5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, 56, 55));

        BT6.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        BT6.setText("BT7");
        BT6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT6ActionPerformed(evt);
            }
        });
        getContentPane().add(BT6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 340, 56, 55));

        BT7.setText("BT0");
        BT7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT7ActionPerformed(evt);
            }
        });
        getContentPane().add(BT7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 56, 55));

        PHOTO_LABEL.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        PHOTO_LABEL.setText("PHOTO:");
        getContentPane().add(PHOTO_LABEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 285, 60, 30));

        trims_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maturita/maturita/patern3.jpg"))); // NOI18N
        getContentPane().add(trims_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 310, 205));

        buttons_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maturita/maturita/red_patern.png"))); // NOI18N
        getContentPane().add(buttons_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 720, 80));

        header.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        header.setText("SPINET Maturitní práce - Marek Novák ");
        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 210, 25));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maturita/maturita/galaxy-720_405.jpg"))); // NOI18N
        background.setPreferredSize(new java.awt.Dimension(725, 405));
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 405));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BT0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BT0ActionPerformed

    private void BT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BT1ActionPerformed

    private void BT2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BT2ActionPerformed

    private void BT3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BT3ActionPerformed

    private void BT4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BT4ActionPerformed

    private void BT5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BT5ActionPerformed

    private void BT6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BT6ActionPerformed

    private void BT7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BT7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BT0;
    private javax.swing.JToggleButton BT1;
    private javax.swing.JToggleButton BT2;
    private javax.swing.JToggleButton BT3;
    private javax.swing.JToggleButton BT4;
    private javax.swing.JToggleButton BT5;
    private javax.swing.JToggleButton BT6;
    private javax.swing.JToggleButton BT7;
    private javax.swing.JLabel PHOTO;
    private javax.swing.JLabel PHOTO_LABEL;
    private javax.swing.JLabel PORTA;
    private javax.swing.JLabel PORTA_arrow;
    private javax.swing.JLabel PORTA_label1;
    private javax.swing.JLabel PORTB;
    private javax.swing.JLabel PORTB_arrow;
    private javax.swing.JLabel PORTB_label;
    private javax.swing.JLabel PORTC;
    private javax.swing.JLabel PORTC_arrow;
    private javax.swing.JLabel PORTC_label;
    private javax.swing.JLabel PORTD;
    private javax.swing.JLabel PORTD_arrow;
    private javax.swing.JLabel PORTD_label;
    private javax.swing.JLabel TEMP;
    private javax.swing.JLabel TRIM1;
    private javax.swing.JLabel TRIM2;
    private javax.swing.JLabel background;
    private javax.swing.JLabel bargraf;
    private javax.swing.JSlider bargraf_slider;
    private javax.swing.JLabel buttons_background;
    private javax.swing.JLabel display;
    private javax.swing.JLabel gren_diode;
    private javax.swing.JLabel header;
    private javax.swing.JLabel hostaname;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel ports_background;
    private javax.swing.JLabel red_diode;
    private javax.swing.JLabel temp_disp;
    private javax.swing.JLabel top_background;
    private javax.swing.JProgressBar trim1_bar;
    private javax.swing.JLabel trim1_disp;
    private javax.swing.JProgressBar trim2_bar;
    private javax.swing.JLabel trim2_disp;
    private javax.swing.JLabel trims_background;
    // End of variables declaration//GEN-END:variables
}
